#!/usr/bin/env bash

sync_dragonfly_images() {
  [[ "${DRAGONFLY_ENABLED:-true}" == "true" ]] || return 0

  DRAGONFLY_MANAGER_IMAGE_REPOSITORY="${DRAGONFLY_MANAGER_IMAGE_REPOSITORY:-dragonflyoss/manager}"
  DRAGONFLY_MANAGER_IMAGE_TAG="${DRAGONFLY_MANAGER_IMAGE_TAG:-v2.4.1}"
  DRAGONFLY_SCHEDULER_IMAGE_REPOSITORY="${DRAGONFLY_SCHEDULER_IMAGE_REPOSITORY:-dragonflyoss/scheduler}"
  DRAGONFLY_SCHEDULER_IMAGE_TAG="${DRAGONFLY_SCHEDULER_IMAGE_TAG:-v2.4.1}"
  DRAGONFLY_CLIENT_IMAGE_REPOSITORY="${DRAGONFLY_CLIENT_IMAGE_REPOSITORY:-dragonflyoss/client}"
  DRAGONFLY_CLIENT_IMAGE_TAG="${DRAGONFLY_CLIENT_IMAGE_TAG:-v1.2.9}"
  DRAGONFLY_BUSYBOX_IMAGE_REPOSITORY="${DRAGONFLY_BUSYBOX_IMAGE_REPOSITORY:-busybox}"
  DRAGONFLY_BUSYBOX_IMAGE_TAG="${DRAGONFLY_BUSYBOX_IMAGE_TAG:-latest}"
  DRAGONFLY_MYSQL_IMAGE_REPOSITORY="${DRAGONFLY_MYSQL_IMAGE_REPOSITORY:-bitnamilegacy/mysql}"
  DRAGONFLY_MYSQL_IMAGE_TAG="${DRAGONFLY_MYSQL_IMAGE_TAG:-8.0.36-debian-12-r10}"
  DRAGONFLY_REDIS_IMAGE_REPOSITORY="${DRAGONFLY_REDIS_IMAGE_REPOSITORY:-bitnamilegacy/redis}"
  DRAGONFLY_REDIS_IMAGE_TAG="${DRAGONFLY_REDIS_IMAGE_TAG:-7.2.5-debian-12-r0}"

  DRAGONFLY_MANAGER_TARGET_REPOSITORY="$(image_sync_target_repo_for_source_repo "${DRAGONFLY_MANAGER_IMAGE_REPOSITORY}")"
  DRAGONFLY_SCHEDULER_TARGET_REPOSITORY="$(image_sync_target_repo_for_source_repo "${DRAGONFLY_SCHEDULER_IMAGE_REPOSITORY}")"
  DRAGONFLY_CLIENT_TARGET_REPOSITORY="$(image_sync_target_repo_for_source_repo "${DRAGONFLY_CLIENT_IMAGE_REPOSITORY}")"
  DRAGONFLY_BUSYBOX_TARGET_REPOSITORY="$(image_sync_target_repo_for_source_repo "${DRAGONFLY_BUSYBOX_IMAGE_REPOSITORY}")"
  DRAGONFLY_MYSQL_TARGET_REPOSITORY="$(image_sync_target_repo_for_source_repo "${DRAGONFLY_MYSQL_IMAGE_REPOSITORY}")"
  DRAGONFLY_REDIS_TARGET_REPOSITORY="$(image_sync_target_repo_for_source_repo "${DRAGONFLY_REDIS_IMAGE_REPOSITORY}")"

  export DRAGONFLY_MANAGER_TARGET_REPOSITORY
  export DRAGONFLY_SCHEDULER_TARGET_REPOSITORY
  export DRAGONFLY_CLIENT_TARGET_REPOSITORY
  export DRAGONFLY_BUSYBOX_TARGET_REPOSITORY
  export DRAGONFLY_MYSQL_TARGET_REPOSITORY
  export DRAGONFLY_REDIS_TARGET_REPOSITORY

  image_sync_write_env_if_available DRAGONFLY_MANAGER_TARGET_REPOSITORY "${DRAGONFLY_MANAGER_TARGET_REPOSITORY}"
  image_sync_write_env_if_available DRAGONFLY_SCHEDULER_TARGET_REPOSITORY "${DRAGONFLY_SCHEDULER_TARGET_REPOSITORY}"
  image_sync_write_env_if_available DRAGONFLY_CLIENT_TARGET_REPOSITORY "${DRAGONFLY_CLIENT_TARGET_REPOSITORY}"
  image_sync_write_env_if_available DRAGONFLY_BUSYBOX_TARGET_REPOSITORY "${DRAGONFLY_BUSYBOX_TARGET_REPOSITORY}"
  image_sync_write_env_if_available DRAGONFLY_MYSQL_TARGET_REPOSITORY "${DRAGONFLY_MYSQL_TARGET_REPOSITORY}"
  image_sync_write_env_if_available DRAGONFLY_REDIS_TARGET_REPOSITORY "${DRAGONFLY_REDIS_TARGET_REPOSITORY}"

  log "Dragonfly image mirror plan:"
  log "  manager    : ${DRAGONFLY_MANAGER_IMAGE_REPOSITORY}:${DRAGONFLY_MANAGER_IMAGE_TAG}"
  log "  scheduler  : ${DRAGONFLY_SCHEDULER_IMAGE_REPOSITORY}:${DRAGONFLY_SCHEDULER_IMAGE_TAG}"
  log "  client     : ${DRAGONFLY_CLIENT_IMAGE_REPOSITORY}:${DRAGONFLY_CLIENT_IMAGE_TAG}"
  log "  busybox    : ${DRAGONFLY_BUSYBOX_IMAGE_REPOSITORY}:${DRAGONFLY_BUSYBOX_IMAGE_TAG}"
  log "  mysql      : ${DRAGONFLY_MYSQL_IMAGE_REPOSITORY}:${DRAGONFLY_MYSQL_IMAGE_TAG}"
  log "  redis      : ${DRAGONFLY_REDIS_IMAGE_REPOSITORY}:${DRAGONFLY_REDIS_IMAGE_TAG}"

  image_sync_import_ref "${DRAGONFLY_MANAGER_IMAGE_REPOSITORY}:${DRAGONFLY_MANAGER_IMAGE_TAG}" "${DRAGONFLY_MANAGER_IMAGE_REPOSITORY}:${DRAGONFLY_MANAGER_IMAGE_TAG}"
  image_sync_import_ref "${DRAGONFLY_SCHEDULER_IMAGE_REPOSITORY}:${DRAGONFLY_SCHEDULER_IMAGE_TAG}" "${DRAGONFLY_SCHEDULER_IMAGE_REPOSITORY}:${DRAGONFLY_SCHEDULER_IMAGE_TAG}"
  image_sync_import_ref "${DRAGONFLY_CLIENT_IMAGE_REPOSITORY}:${DRAGONFLY_CLIENT_IMAGE_TAG}" "${DRAGONFLY_CLIENT_IMAGE_REPOSITORY}:${DRAGONFLY_CLIENT_IMAGE_TAG}"
  image_sync_import_ref "${DRAGONFLY_BUSYBOX_IMAGE_REPOSITORY}:${DRAGONFLY_BUSYBOX_IMAGE_TAG}" "${DRAGONFLY_BUSYBOX_IMAGE_REPOSITORY}:${DRAGONFLY_BUSYBOX_IMAGE_TAG}"
  image_sync_import_ref "${DRAGONFLY_MYSQL_IMAGE_REPOSITORY}:${DRAGONFLY_MYSQL_IMAGE_TAG}" "${DRAGONFLY_MYSQL_IMAGE_REPOSITORY}:${DRAGONFLY_MYSQL_IMAGE_TAG}"
  image_sync_import_ref "${DRAGONFLY_REDIS_IMAGE_REPOSITORY}:${DRAGONFLY_REDIS_IMAGE_TAG}" "${DRAGONFLY_REDIS_IMAGE_REPOSITORY}:${DRAGONFLY_REDIS_IMAGE_TAG}"
}